/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_promu_caireen_jni_service_ImageProcessor */

#ifndef _Included_kr_promu_caireen_jni_service_ImageProcessor
#define _Included_kr_promu_caireen_jni_service_ImageProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kr_promu_caireen_jni_service_ImageProcessor
 * Method:    processImage
 * Signature: ([BIII)I
 */
JNIEXPORT jint JNICALL Java_kr_promu_caireen_jni_service_ImageProcessor_processImage
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
